### PR TITLE
Feature/serve static website

### PR DESCRIPTION
**Pull request by mms-gianni**
It does work pretty well.

I've added an .env.example. This file might be not complete. 

image

### CODE REVIEW

**Comment by mms-gianni** [comment]
Just found this missing js. 🤔 
image

**Comment by emanuelef** [comment]
> Just found this missing js. 🤔 image

Yes, this is probably required by Fusion Chart to export to Excel, not sure if there's a way to disable it. From Fusion Chart the two only exports used are to PNG and PDF.

**Review by emanuelef — APPROVED** [review]

**Comment by emanuelef** [comment]
This looks good to me, only downside is that the Docker image will be a bit bigger because it contains the UI, but should be minimal I suppose. I can compare the resulting size when is built.

**Comment by emanuelef** [comment]
Should probably work with the current way the app is deployed on OCI and GH Pages.
Some more details here: https://medium.com/stackademic/building-a-cost-free-always-on-personal-project-stack-3eaa02ac16b6.

**Pull request merged**
